server.port=8081
spring.application.name=inventory-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=postgres
spring.datasource.password=Alex1999@_
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ? auto-creates tables on startup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka
#eureka.client.service-url.defaultZone=http://localhost:9000/eureka/
#eureka.instance.prefer-ip-address=true
