server.port=8081
spring.application.name=inventory-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=postgres
spring.datasource.password=Alex1999@_
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ? auto-creates tables on startup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.show-actuator=false
springdoc.api-docs.groups.enabled=true
springdoc.use-fqn=true

# Actuator endpoints
management.endpoints.web.exposure.include=health,info,env
management.endpoint.health.show-details=when-authorized

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springdoc=DEBUG
logging.level.org.kariioke.inventoryservice=DEBUG

# Eureka
#eureka.client.service-url.defaultZone=http://localhost:9000/eureka/
#eureka.instance.prefer-ip-address=true
